output = "Generated/GeneratedMocks.swift"

[modules.TheKata]
output = "Generated/GeneratedMocks+TheKata.swift"
imports = ["Foundation"]
sources = [
    "TheKata/*.swift",
]

[modules.TheKata.options]
keepDocumentation = false
protocolsOnly = true

# If specified, Cuckoo can also get sources for the module from an Xcode target.
#[modules.TheKata.xcodeproj]
# Path to folder with .xcodeproj, omit this if it's at the same level as Cuckoofile.
#path = "Generator"
#target = "Cuckoonator"